#!/usr/bin/env node

const
  { ethers } =
    require(
      "ethers");
_ethers =
  ethers;
_contract_factory =
  _ethers.ContractFactory;
const
  _fs_utils =
    require(
      '../libcrash-js/fs-utils');
_dirname =
  _fs_utils._dirname;
_file_read =
  _fs_utils._file_read;
_path_join =
  _fs_utils._path_join;
const
  _libcrash =
    require(
      '../libcrash-js/crash-js');
_msg_info =
  _libcrash._msg_info;
_msg_error =
  _libcrash._msg_error;
const
  _wallet_get_module =
    require(
      '../evm-wallet/wallet-get');
_wallet_get =
  _wallet_get_module._wallet_get;
const
  _network_provider =
    require(
      '../evm-wallet/network-provider');
_provider_get =
  _network_provider._provider_get;

function
  _global_variables() {
  app_name =
    "deployer";
  wallet_seed =
    "";
  contract_bytecode_path =
    "";
  target_network =
    "";
  api_key_path =
    "";
  quiet =
    "";
}


function
  _msg_info_provider_generated(
    _provider) {
  let
    _msg,
    _template;
  _template =
    "provider '{_provider}' generated";
  _msg =
    _template.replaceAll(
      "{_provider}",
      _provider);
  _msg_info(
    _msg);
}


function
  _msg_info_contract_deployed(
    _contract) {
  let
    _msg,
    _template;
  _template =
    "deployed contract '{_contract}'";
  _msg =
    _template.replaceAll(
      "{_contract}",
      _contract);
  _msg_info(
    _msg);
}


async function
  _evm_deployer(
    _wallet_seed,
    _contract_bytecode_path,
    _target_network,
    _api_key_path) {
  let
    _api_key,
    _contract,
    _contract_bytecode,
    _factory,
    _wallet,
    _wallet_get_opts,
    _wallet_password,
    _wallet_path_list,
    _wallet_path;
  _wallet_password =
    "";
  _wallet_path_list = [
    _dirname(
      _wallet_seed),
    "wallet.dat"
  ];
  _wallet_path =
    _path_join(
      _wallet_path_list);
  _api_key =
    _file_read(
      _api_key_path);
  _contract_bytecode =
    _file_read(
      _contract_bytecode_path);
  _provider =
    _provider_get(
      _target_network,
      _api_key);
  _msg_info_provider_generated(
    _provider);
  _wallet_get_opts=[
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _provider
  ];
  _wallet =
    _wallet_get.apply(
      null,
      _wallet_get_opts);
  _factory =
    _contract_factory.fromSolidity(
      _contract_bytecode);
  _factory =
    _factory.connect(
      _wallet);
  _contract = await
    _factory.deploy();
  _msg_info_contract_deployed(
    _contract);
  console.log(
    _contract.target);
}

function
  _config_show() {
  let
    _line,
    _text;
  _text =
    [];
  _text.push(
    "      Wallet seed: {wallet_seed}".replace(
      "{wallet_seed}",
      wallet_seed));
  _text.push(
    "   Target network: {target_network}".replace(
      "{target_network}",
      target_network));
  _text.push(
    "          API Key: {api_key}".replace(
      "{api_key}",
      api_key_path));
  _text.push(
    "Contract bytecode: {contract_bytecode}".replace(
      "{contract_bytecode}",
      contract_bytecode_path));
  for ( _line in _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage() {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  deployer",
    "    <quiet>",
    "    <seed_path>",
    "    <contract_bytecode>",
    "    (<target_network>)",
    "    (<api_key>)"];
  for ( _line in _text ) {
    _msg_info(
      _line);
  }
  process.exit();
}


function _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _index == 5 ) {
        target_network =
          _value;
      }
      if ( _index == 6 ) {
        api_key_path =
          _value;
      }
  });
  if ( contract_bytecode_path == "" ) {
    _usage();
  }
}

_global_variables();

if ( require.main == module ) {
  _cmdline_parse();
  _config_show();
  app_opts = [
    wallet_seed,
    contract_bytecode_path,
    target_network,
    api_key_path,
  ];
  _evm_deployer.apply(
    null,
    app_opts);
}

module.exports = {
  _evm_deployer:
    _evm_deployer
};
