#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_libevm="${_lib}/libevm/libevm"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"
_sourced \
  "${_libevm}"

# shellcheck disable=SC2034
_global_variables() {
  deploy_date=""
  target_contracts=()
  wallet_path=""
  wallet_password=""
  wallet_seed=""
  wallet_address=""
  target_network=""
  rpc_selection=""
  contract_abi=""
  contract_bytecode=""
  contract_compiler_output=""
  compiler_backend=""
  evm_version=""
  solc_version=""
  api_key=""
  wallet_name=""
  retries_max=""
  call_timeout=""
  output_file=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'evm-chains-info'
  _check_cmd \
    'evm-wallet'
  _check_cmd \
    'node-run'
  _check_cmd \
    'solidity-compiler'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/${app_name}"
  echo \
    "${_dir}"
}

_evm_deployer() {
  local \
    _wallet_path="${1}" \
    _wallet_password="${2}" \
    _wallet_seed="${3}" \
    _network="${4}" \
    _rpc_selection="${5}" \
    _api_key_path="${6}" \
    _contract_abi_path="${7}" \
    _contract_bytecode_path="${8}" \
    _contract_compiler_output_path="${9}" \
    _compiler_backend="${10}" \
    _solc_version="${11}" \
    _evm_version="${12}" \
    _retries_max="${13}" \
    _call_timeout="${14}" \
    _cache_dir="${15}" \
    _output_file="${16}" \
    _target_contracts=() \
    _node_run_opts=() \
    _contract_filename \
    _contract_name \
    _cmd \
    _args=() \
    _rpc_backend \
    _tmp
  shift \
    16
  _target_contracts+=(
    "$@"
  )
  _node_run_opts+=(
    -r
      "${_retries_max}"
  )
  _cmd="$( \
    _get_lib)/${app_name}/deployer"
  _rpc_backend_get \
    "${_network}" \
    "${_rpc_selection}"
  if [[ "${_contract_bytecode_path}" == "" && \
        "${_contract_compiler_output_path}" == "" ]]; then
    _contract_filename="$( \
      basename \
        "${_target_contracts}")"
    _contract_name="${_contract_filename%%.*}"
    _bytecode_dir="$( \
      mktemp \
        -d)"
    _solidity_compiler_opts+=(
      -o
        "${_bytecode_dir}"
    )
    if [[ "${_compiler_backend}" != "" ]]; then
      _solidity_compiler_opts+=(
        -b
          "${_compiler_backend}"
      )
    fi
    if [[ "${_solc_version}" != "" ]]; then
      _solidity_compiler_opts+=(
        -C
          "${_solc_version}"
      )
    fi
    if [[ "${_evm_version}" != "" ]]; then
      _solidity_compiler_opts+=(
        -e
          "${_evm_version}"
      )
    fi
    solidity-compiler \
      "${_solidity_compiler_opts[@]}" \
      "${_target_contracts[@]}"
    _contract_abi="${_bytecode_dir}/${_contract_name}.abi.json"
    _contract_bytecode="${_bytecode_dir}/${_contract_name}.bin"
    _contract_compiler_output="${_bytecode_dir}/contracts/${_contract_name}.sol/${_contract_name}.json"
  fi
  _args+=(
    "${quiet}"
    "${_retries_max}"
    "${_call_timeout}"
    "${_wallet_seed}"
    "${_contract_abi_path}"
    "${_contract_bytecode_path}"
    "${_contract_compiler_output_path}"
    "${_rpc_backend}"
    "${_api_key_path}"
    "${_output_file}"
  )
  _msg_info \
    "Running node with options '${_args[*]}'."
  node-run \
    "${_node_run_opts[@]}" \
    "${_cmd}" \
    "${_args[@]}"
}

_contract_bytecode_auto_detect() {
  local \
    _bytecode \
    _name \
    _source \
    _target
  _bytecode=""
  _source="${target_contracts}"
  _name="${_source%.*}"
  _target="${_name}.bin"
  if [ -e "${_target}" ]; then
    _bytecode="${_target}"
  fi
  _set_override \
    "contract" \
    "bytecode" \
    "${_bytecode}"
}

_file_hash() {
  local \
    _file="${1}"
  sha256sum \
    "${_file}" | \
    awk \
      '{print $1}'
}

# This works with a single file actually
_output_file_auto_detect() {
  local \
    _cache_dir \
    _output_dir \
    _output_file \
    _contract_name \
    _contract_dir \
    _network_dir
  _contract_name="$( \
    basename \
      "${target_contracts[0]}")"
  _contract_hash="$( \
    _file_hash \
      "${target_contracts[0]}")"
  _contract_dir="${cache_dir}/${_contract_name}/${_contract_hash}"
  _output_dir="${_contract_dir}/${target_network}"
  _output_file="${_output_dir}/contract.json"
  mkdir \
    -p \
    "${_output_dir}" || \
    true
  chmod \
    700 \
    "${_output_dir}"
  _set_override \
    "output" \
    "file" \
    "${_output_file}"
}


_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "deploy" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "cache" \
    "dir" \
    "${HOME}/.cache/${app_name}"
  _set_override \
    "wallet" \
    "name" \
    "default"
  _set_override \
    "target" \
    "network" \
    "Gnosis"
  _set_override \
    "rpc" \
    "selection" \
    "kirsh"
  _api_key_auto_detect \
    "${target_network}"
  _set_override \
    "wallet" \
    "path" \
    "$(_wallet_path_get \
         "evm-wallet" \
         "${wallet_name}")"
  _secret_auto_detect \
    "seed" \
    "seed" \
    "evm-wallet" \
    "${wallet_name}"
  _secret_auto_detect \
    "password" \
    "plain" \
    "evm-wallet" \
    "${wallet_name}"
  _set_override \
    "wallet" \
    "address" \
    "$(evm-wallet \
         get \
           "${wallet_name}" \
           "address")"
  _set_override \
    "compiler" \
    "backend" \
    ""
  _set_override \
    "solc" \
    "version" \
    ""
  _set_override \
    "evm" \
    "version" \
    ""
  _set_override \
    "retries" \
    "max" \
    "10"
  _set_override \
    "call" \
    "timeout" \
    "300"
  if [[ "${target_contracts[*]}" != "" ]]; then
    _set_override \
      "contract" \
      "abi" \
      ""
    _set_override \
      "contract" \
      "compiler_output" \
      ""
    _contract_bytecode_auto_detect
    _output_file_auto_detect
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _networks_amount \
    _usage_text
  _networks_amount="$( \
    evm-chains-info \
      -i \
        "amount")"
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
EVM network deployer

Usage:
  ${app_name}
    [options]
    <contract_file>

  networks:
    total EVM networks available:
      ${_networks_amount}
    see which with "evm-chains-info"

  options:
     -w <wallet_path>                Wallet path.
                                     Default: ${wallet_path}
     -p <wallet_password>            Wallet password.
                                     Default: ${wallet_password}
     -s <wallet_seed>                Wallet seed path.
                                     Default: ${wallet_seed}
     -n <network>                    EVM network name.
                                     Default: ${target_network}
     -R <rpc_selection>              RPC selection method.
                                     Default: ${rpc_selection}
     -k <api_key>                    Etherscan-like service key.
                                     Default: ${api_key}
     -A <contract_abi>               Contract ABI.
                                     Default: ${contract_abi}
     -B <contract_bytecode>          Contract bytecode.
                                     Default: ${contract_bytecode}
     -O <contract_compiler_output>   Contract compiler output.
                                     Default: ${contract_compiler_output}
     -b <compiler_backend>           It can be 'solc' or 'hardhat'.
                                     Default: ${compiler_backend}
     -C <solc_version>               Solc version.
                                     Default: ${solc_version}
     -e <evm_version>                EVM version.
                                     Default: ${evm_version}
     -r <retries_max>                Maximum number of retries before
                                     failing.
                                     Default: ${retries_max}
     -T <call_timeout>               Maximum number of seconds before
                                     declaring the call failed.
                                     Default: ${call_timeout}
     -W <cache_dir>                  Work directory.
                                     Default: ${cache_dir}
     -o <output_file>                Where to save a JSON representing
                                     the contract object resulting from
                                     the deployment.
                                     Default: ${output_file}

     -h                              This message.
     -c                              Enable color output
     -v                              Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "              Deploy date:   ${deploy_date}"
  _msg_info "              Wallet path:   ${wallet_path}"
  _msg_info "          Wallet password:   ${wallet_password}"
  _msg_info "              Wallet seed:   ${wallet_seed}"
  _msg_info "           Target network:   ${target_network}"
  _msg_info "     RPC selection method:   ${rpc_selection}"
  _msg_info "                  API key:   ${api_key}"
  _msg_info "             Contract ABI:   ${contract_abi}"
  _msg_info "        Contract bytecode:   ${contract_bytecode}"
  _msg_info " Contract compiler output:   ${contract_compiler_output}"
  _msg_info "             Solc version:   ${solc_version}"
  _msg_info "              EVM version:   ${evm_version}"
  _msg_info "         Compiler backend:   ${compiler_backend}"
  _msg_info "          Maximum retries:   ${retries_max}"
  _msg_info "          Cache directory:   ${cache_dir}"
  _msg_info "              Output file:   ${output_file}"
  _msg_info "         Target contracts:   ${target_contracts[*]}"
}

_globals
_global_variables
_requirements
_config_user_init \
  "${app_name}"
# shellcheck disable=SC2034
while \
  getopts \
    'w:p:s:n:R:k:b:C:e:A:B:O:r:T:W:o:cvh?' \
    arg; do
  case \
    "${arg}" in
    w) override_wallet_path="${OPTARG}" ;;
    p) override_wallet_password="${OPTARG}" ;;
    s) override_wallet_seed="${OPTARG}" ;;
    n) override_target_network="${OPTARG}" ;;
    R) override_rpc_selection="${OPTARG}" ;;
    k) override_api_key="${OPTARG}" ;;
    b) override_compiler_backend="${OPTARG}" ;;
    C) override_solc_version="${OPTARG}" ;;
    e) override_evm_version="${OPTARG}" ;;
    A) override_contract_abi="${OPTARG}" ;;
    B) override_contract_bytecode="${OPTARG}" ;;
    O) override_contract_compiler_output="${OPTARG}" ;;
    r) override_retries_max="${OPTARG}" ;;
    T) override_call_timeout="${OPTARG}" ;;
    W) override_cache_dir="${OPTARG}" ;;
    o) override_output_file="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( 0 == $# )); then
  _msg_error \
    "no contracts given" \
    1
fi
target_contracts+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${target_network}"
  "${rpc_selection}"
  "${api_key}"
  "${contract_abi}"
  "${contract_bytecode}"
  "${contract_compiler_output}"
  "${compiler_backend}"
  "${solc_version}"
  "${evm_version}"
  "${retries_max}"
  "${call_timeout}"
  "${cache_dir}"
  "${_output_file}"
  "${target_contracts[@]}"
)
_evm_deployer \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
